services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    # Add a .env file containing the values of this variables
    environment:
      - DATA_CURATION_CLIENT_ID
      - DATA_CURATION_CLIENT_SECRET
      - DATA_CURATION_API_URL
      - DATA_CURATION_OAUTH_URL
      - CONTEXT_ENRICHMENT_CLIENT_ID
      - CONTEXT_ENRICHMENT_CLIENT_SECRET
      - CONTEXT_ENRICHMENT_API_URL
      - CONTEXT_ENRICHMENT_OAUTH_URL