logging:
  level:
    root: INFO                      # Default log level
    org.springframework.web: DEBUG  # Log incoming web requests in detail
    org.apache.http: DEBUG          # Log HTTP client requests/responses

server:
  port: 8080  # Application server port

app:
  data-curation:                                   # MUST be provided as environment variables
    client-id: ${DATA_CURATION_CLIENT_ID}          # OAuth client ID for Data Curation service
    client-secret: ${DATA_CURATION_CLIENT_SECRET}  # OAuth client secret
    api-url: ${DATA_CURATION_API_URL}              # Base API URL for Data Curation
    oauth-url: ${DATA_CURATION_OAUTH_URL}          # OAuth token endpoint for Data Curation

  context-enrichment:                                   # MUST be provided as environment variables
    client-id: ${CONTEXT_ENRICHMENT_CLIENT_ID}          # OAuth client ID for Context Enrichment service
    client-secret: ${CONTEXT_ENRICHMENT_CLIENT_SECRET}  # OAuth client secret
    api-url: ${CONTEXT_ENRICHMENT_API_URL}              # Base API URL for Context Enrichment
    oauth-url: ${CONTEXT_ENRICHMENT_OAUTH_URL}          # OAuth token endpoint for Context Enrichment

  security:
    token-cache-duration: PT50M  # Duration to cache OAuth tokens (50 minutes)
    max-retries: 3               # Number of retry attempts for failed requests
    retry-delay: PT1S            # Delay between retries (1 second)

  rest-template:
    connect-timeout: PT5S          # Connection timeout for HTTP requests (5 seconds)
    read-timeout: PT30S            # Read timeout for HTTP responses (30 seconds)
    max-connections: 100           # Total max HTTP connections
    max-connections-per-route: 20  # Max connections per route (host)
